{% set name = "OpenRAFT" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/OpenRAFT-{{ version }}.tar.gz
  sha256: 3938270dee95c4d950f9ab8c26fba9c46c455b33c5cb84495a917cb62a280e47

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools
    - pip
  run:
    - matplotlib-base
    - moorpy
    - numpy
    - openmdao
    - pyhams
    - python >=3.9
    - pyyaml
    - scipy
    - wisdem

test:
  imports:
    - raft

about:
  home: https://github.com/wisdem/raft
  summary: "RAFT: Response Amplitudes of Floating Turbines"
  description: |
    RAFT is a frequency domain analysis tool of floating offshore wind turbines
    that uses either strip theory or the HAMS boundary element method solver.
  license: Apache-2.0
  license_file: LICENSE
  dev_url: https://github.com/wisdem/raft

extra:
  recipe-maintainers:
    - gbarter
    - mattEhall
