{% set name = "OpenRAFT" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/WISDEM/RAFT/archive/v{{ version }}.tar.gz
    # Download the tar-ball and do: openssl sha256 file.tar.gz to update
  sha256: a44bfb33a5f8b646c69b5f6a6e53a34f2481b4481bd2c13c886853128e55839e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools
    - pip
  run:
    - matplotlib-base
    - moorpy
    - numpy <2.0dev0
    - openmdao
    - pyhams
    - python >=3.9
    - pyyaml
    - scipy
    - wisdem

test:
  imports:
    - raft

about:
  home: https://github.com/wisdem/raft
  summary: "RAFT: Response Amplitudes of Floating Turbines"
  description: |
    RAFT is a frequency domain analysis tool of floating offshore wind turbines
    that uses either strip theory or the HAMS boundary element method solver.
  license: Apache-2.0
  license_file: LICENSE
  dev_url: https://github.com/wisdem/raft

extra:
  recipe-maintainers:
    - gbarter
    - mattEhall
