{% set name = "OpenRAFT" %}
{% set version = "1.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/OpenRAFT-{{ version }}.tar.gz
  sha256: 59be0d0f26de22bf695e7b92bade6548afcafe22d341c00101c89d6cb615e515
  
build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools
    - pip
  run:
    - matplotlib-base
    - moorpy
    - numpy
    - openmdao
    - pyhams
    - python >=3.9
    - pyyaml
    - scipy
    - wisdem

test:
  imports:
    - raft

about:
  home: https://github.com/wisdem/raft
  summary: "RAFT: Response Amplitudes of Floating Turbines"
  description: |
      RAFT is a frequency domain analysis tool of floating offshore wind turbines
      that uses either strip theory or the HAMS boundary element method solver.
  license: Apache-2.0
  license_file: LICENSE
  dev_url: https://github.com/wisdem/raft

extra:
  recipe-maintainers:
    - gbarter
    - mattEhall
