{% set name = "OpenRAFT" %}
{% set version = "1.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/WISDEM/RAFT/archive/v{{ version }}.tar.gz
    # Download the tar-ball and do: openssl sha256 file.tar.gz to update
  sha256: ada1ed0f8ed0bc22e3e37e5c2a9ce542f7a33973410cefb82ca13a4382d7c521

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools
    - pip
  run:
    - matplotlib-base
    - moorpy
    - numpy
    - openmdao
    - pyhams
    - python >=3.9
    - pyyaml
    - ruamel.yaml
    - scipy
    - wisdem

test:
  # Imports won't work without ORBIT  
  #imports:
  #  - raft
  requires:
    - pip
  source_files:
    - raft
    - examples
  commands:
    - pip install orbit-nrel
    - cd examples
    - python example_from_yaml.py false
    - cd ..

about:
  home: https://github.com/wisdem/raft
  summary: "RAFT: Response Amplitudes of Floating Turbines"
  description: |
    RAFT is a frequency domain analysis tool of floating offshore wind turbines
    that uses either strip theory or the HAMS boundary element method solver.
  license: Apache-2.0
  license_file: LICENSE
  dev_url: https://github.com/wisdem/raft

extra:
  recipe-maintainers:
    - gbarter
    - mattEhall
